name: 'ipea'

version: 1.0.0
config-version: 2

profile: ipea

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ipea: 
    contratos:
      +materialized: table
      +database: analytics
      +schema: contratos
      bronze:
        +materialized: incremental
        +unique_key: id
    pessoas:
      +materialized: table
      +database: analytics
      +schema: pessoas

on-run-start:
  - '{{create_udfs()}}'