name: 'ipea'

version: 1.0.0
config-version: 2

profile: ipea

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ipea: 
    +database: analytics
    contratos_dbt:
      +materialized: table
      +schema: contratos
      bronze:
        +materialized: incremental
      views:
        +materialized: view
    pessoas_dbt:
      +materialized: table
      +schema: pessoas
      views:
        +materialized: view
    ted_dbt:
      +materialized: table
      +schema: ted
      views:
        +materialized: view

on-run-start:
  - '{{create_udfs()}}'