ipea:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_DW_HOST', 'postgres') }}"
      user: "{{ env_var('DB_DW_USER', 'postgres_dw') }}"
      password: "{{ env_var('DB_DW_PASSWORD', 'postgres_dw') }}"
      port: "{{ env_var('DB_DW_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_DW_DBNAME', 'data_warehouse') }}"
      schema: "{{ env_var('DB_DW_SCHEMA', 'ipea') }}"