# Este arquivo deve ser usado para descrições dos modelos
# e para configurar testes

version: 2

models:

  # Contratos DBT

  ## Bronze
  - name: contratos
    description: >
      Tabela com informações sobre contratos, incluindo detalhes como o valor do contrato, a data de início e término, e o status do contrato.
      Esta tabela é fundamental para entender a execução e o cumprimento dos contratos firmados.
      A tabela é atualizada diariamente e contém dados de contratos firmados pelo IPEA.
    columns:
      - name: id
        description: >
          Identificador único do contrato, utilizado para referenciar o contrato em outras tabelas e análises.
    data_tests: 
      - row_count_match:
          source_table: compras_gov.contratos
          target_table: contratos.contratos
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'num_parcelas'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'valor_inicial'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'valor_global'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'valor_parcela'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'valor_acumulado'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'data_assinatura'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'data_publicacao'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'data_proposta_comercial'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'vigencia_inicio'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.contratos'
          nome_coluna: 'vigencia_fim'
          tipo_esperado: 'date'

  - name: cronogramas
    description: >
      Essa tabela contém informações sobre as despesas mensais programadas cada contrato.
    data_tests: 
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'id'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'contrato_id'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'mesref'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'anoref'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'valor'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.cronogramas'
          nome_coluna: 'vencimento'
          tipo_esperado: 'date'

  - name: faturas
    description: "Essa tabela contém informações sobre as faturas emitidas mensalmente de cada contrato."
    data_tests:
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'id'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'contrato_id'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'emissao'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'prazo'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'vencimento'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'valor'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'juros'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'multa'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'glosa'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'valorliquido'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'protocolo'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'ateste'
          tipo_esperado: 'date'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'mesref'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.faturas'
          nome_coluna: 'anoref'
          tipo_esperado: 'integer'

  - name: empenhos
    description: >
      Essa tabela contém informações sobre os empenhos de cada contrato.
    data_tests: 
      - row_count_match:
          source_table: compras_gov.empenhos
          target_table: contratos.empenhos
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'empenhado'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'aliquidar'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'liquidado'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'pago'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'rpinscrito'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'rpaliquidar'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'rpliquidado'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'rppago'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos'
          nome_coluna: 'data_emissao'
          tipo_esperado: 'date'


  - name: empenhos_tesouro
    description: >
      Essa tabela contém informações sobre movimentação financeira dos empenhos extraídos do SIAFI.

    data_tests:
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'ne_ccor_ano_emissao'
          tipo_esperado: 'integer'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'despesas_empenhadas'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'despesas_liquidadas'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'despesas_pagas'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'restos_a_pagar_inscritos'
          tipo_esperado: 'numeric'
      - verificacao_tipagem:
          nome_tabela: 'contratos.empenhos_tesouro'
          nome_coluna: 'restos_a_pagar_pagos'
          tipo_esperado: 'numeric'

  - name: estagios
    description: >
      Essa tabela contém informações sobre os evento de cada empenho discriminados por mês.
    data_tests:
      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'natureza_despesa'
          tipo_esperado: 'integer'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'natureza_despesa_detalhada'
          tipo_esperado: 'integer'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'ano_lancamento'
          tipo_esperado: 'integer'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'ne_ccor_ano_emissao'
          tipo_esperado: 'integer'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_empenhadas_controle_empenho_saldo_moeda_origem'
          tipo_esperado: 'numeric'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_empenhadas_controle_empenho_movim_liquido_moeda_origem'
          tipo_esperado: 'numeric'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_liquidadas_controle_empenho_saldo_moeda_origem'
          tipo_esperado: 'numeric'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_liquidadas_controle_empenho_movim_liquido_moeda_origem'
          tipo_esperado: 'numeric'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_pagas_controle_empenho_saldo_moeda_origem'
          tipo_esperado: 'numeric'

      - verificacao_tipagem:
          nome_tabela: 'contratos.estagios'
          nome_coluna: 'despesas_pagas_controle_empenho_movim_liquido_moeda_origem'
          tipo_esperado: 'numeric'

  ## Silver
  - name: contratos_empenhos
    description: Essa tabela combina as informações de movimentação financeira dos empenhos com os ids de contrato do IPEA.

  - name: contratos_estagios
    description: >
      Essa tabela combina as informações de movimentação financeira dos empenhos com os ids de contrato do IPEA mensalmente.
  
  - name: estagios_mensal
    description: >
      Essa tabela discrimina os valores empenhados, liquidados e pagos mensalmente extraídos do SIAFI para cada contrato.
  
  - name: cronogramas_fatura_mensal
    description: >
      Essa tabela discrimina os falores programados e faturados mensalmente pelo ComprasGov para cada contrato.

  ## Golds
  - name: contratos_resumo
    description: >
      Essa tabela contém um resumo dos contratos, informações contratuais como valor global e valor pago, 
      e situação atual, como em vigência ou pendente de baixa.

  - name: contratos_comparativo_mensal
    description: >
      Essa tabela contém um comparativo mensal dos contratos, discriminando 
      os valores empenhados, liquidados e pagos do SIAFI, 
      programados e faturados do ComprasGov.

  ## View
  - name: identificadores
    description: >
      Essa tabela contém os identificadores dos contratos, empenhos e faturas, 
      Essa tabela é utilizada para facilitar joins.

  # Pessoas DBT

  # TED DBT
  - name: pf_tesouro
    description: >
      Dados das programações financeiras extraídas do SIAFI, com informações sobre o tipo de programação, a data de execução e o valor.
      Essa tabela é atualizada diariamente.
    data_tests:
        - verificacao_tipagem:
            nome_tabela: 'ted.pf_tesouro'
            nome_coluna: 'emissao_dia'
            tipo_esperado: 'date'
        - verificacao_tipagem:
            nome_tabela: 'ted.pf_tesouro'
            nome_coluna: 'pf_valor_linha'
            tipo_esperado: 'numeric'

  - name: empenhos_plano_acao
    description: >
      Dados dos empenhos extraídos do SIAFI, incluído o identificador do plano de ação.
      Essa tabela é atualizada diariamente.

  - name: nc_plano_acao
    description: >
      Dados das notas de crédito extraídas do SIAFI, incluso o identificador do plano de ação.
      Essa tabela é atualizada diariamente.

  - name: pf_plano_acao
    description: >
      Dados das programações financeiras extraídas do SIAFI, includo o identificador do plano de ação.
      Essa tabela é atualizada diariamente.

macros:
  - name: create_udfs
    description: >
      Função que cria as UDFs necessárias para o funcionamento do projeto.
      Essa função deve ser chamada no início de cada run para garantir que todas as UDFs estejam disponíveis.
  
  - name: generate_schema_name
    description: >
      Função que gera o nome do schema a ser utilizado no projeto.
      A função dentro desta macro é built-in do dbt.
  
  ## UDFS
  - name: create_f_parse_dates
    description: >
      Função que cria a UDF f_parse_dates, que é utilizada para converter texto no formato MÊS(texto)/ANO(numero) em datas.
    arguments:
      - name: in_text
        type: text
        description: >
          Texto a ser convertido em data.
          O texto deve estar no formato MÊS(texto)/ANO(numero). Ex.: FEV/2024 -> 2024-02-01