version: 2

sources:
  - name: compras_gov
    schema: compras_gov
    tables:
      - name: contratos
      - name: faturas
      - name: empenhos
      - name: cronograma
  
  - name: siafi
    schema: siafi
    tables:
      - name: empenhos_tesouro
      - name: estagios

