version: 2

sources:
  - name: compras_gov
    schema: compras_gov
    tables:
      - name: contratos
      - name: faturas
      - name: empenhos
      - name: cronograma
  
  - name: siafi
    schema: siafi
    tables:
      - name: empenhos_tesouro
      - name: estagios_tesouro
      - name: nc_tesouro
      - name: pf_tesouro
  
  - name: transfere_gov
    schema: transfere_gov
    tables:
      - name: notas_de_credito
      - name: planos_acao
      - name: programacao_financeira
      - name: programas
  - name: siape 
    schema: siape 
    tables:
      - name: lista_uorgs 
      - name: lista_servidores
      - name: dados_uorg
      - name: dados_pessoais
      - name: dados_pa

