orgaos:
  ipea:
    codigos_ug:
      - 113601
      - 113602
  unb:
    codigos_ug:
      - 154040
  ibama:
    codigos_ug:
      - 440001
      - 440048
      - 440050
  mgi:
    codigos_ug:
      - 201082